### ISSUE TITLE
Hostname of NodeMCU

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-mcuiot#10]
Hi,

is there a way to rename the NodeMCU module? So it will be show with a different name as e.g. "Node-xxx" in Homekit apps?

**Comment by NorthernMan54** [comment]
The config.json setting aliases allows this, please review the README.


"platforms": [ { "platform":	"mcuiot", "name": "MCUIOT", "aliases": { "NODE-2BA4CB": "Front Porch", "NODE-8F8FE": "Cold Cellar", "NODE-DC4492": "Office", "NODE-DC4492GD": "Garage Door" } } ],

**Comment by chimcen** [comment]
Thank you - i‘ve seen the readme aleady - i just ask, because in your blog are still remain the original hostnames...

![image](https://user-images.githubusercontent.com/22658487/45187286-77083100-b230-11e8-8bf1-69383ced6b9c.png)

**Comment by NorthernMan54** [comment]
I keep meaning to go back and update the instructable but never find the time.  Tks for reminding me.
