### ISSUE TITLE
Error starting homebridge after install homebridge-mcuiot

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-mcuiot#11]
Hi,

i've tried to install homebridge with mcuiot plugin.
But after installing mcuiot i got this errors instead:

`root@Raspi:/home/pi# homebridge
[2018-9-7 02:24:47] Loaded config.json with 0 accessories and 1 platforms.
[2018-9-7 02:24:47] ---
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-9-7 02:24:48] Loaded plugin: homebridge-mcuiot
[2018-9-7 02:24:48] Registering platform 'homebridge-mcuiot.mcuiot'
[2018-9-7 02:24:48] ---
[2018-9-7 02:24:48] Loading 1 platforms...
[2018-9-7 02:24:48] [MCUIOT] Initializing mcuiot platform...
[2018-9-7 02:24:48] Loading 0 accessories...
[2018-9-7 02:24:48] [MCUIOT] configureAccessory MCUIOT Reset Switch
Setup Payload:
X-HM://0023ISZEXOJJ6
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
...........................................................................................
[2018-9-7 02:24:48] [MCUIOT] Starting mDNS listener
[2018-9-7 02:24:48] Homebridge is running on port 51826.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at Object.exports.init (/usr/local/lib/node_modules/homebridge-mcuiot/lib/web.js:27:12)
    at mcuiot.didFinishLaunching (/usr/local/lib/node_modules/homebridge-mcuiot/index.js:167:20)
    at API.emit (events.js:180:13)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
Emitted 'error' event at:
    at emitErrorNT (net.js:1365:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
`

Any advice?

Performed on my raspberry pi 3 a fresh install of raspian stretch.

My DHT22 with NodeMCU is configured properly and runnung (values from webinterface when hitting ip adress of the NodeMCU):
`{ "Hostname": "NODE-41E2B", "Model": "DHT", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 24.9, "Humidity": 57.3, "Moisture": 0, "Status": 0, "Barometer": -999, "Dew": -999 }}`

or by sending `dns-sd -B _dht22._tcp` by cmd on my win10 machine:
![image](https://user-images.githubusercontent.com/22658487/45192148-015b8f80-b247-11e8-94d0-03dbed0f1628.png)

Content of config.json:
{
        "bridge": {
                "name": "Homebridge",
                "username": "CD:22:3D:E3:CE:97",
                "port": 51826,
                "pin": "031-45-801"
        },
        
        "platforms": [
				{
					"platform": "mcuiot",
					"name": "MCUIOT",
					"aliases": {
						"NODE-41E2B": "Wohnzimmer"
								}
				}
		],
        
        "accessories": []
}

**Comment by NorthernMan54** [comment]
With the plugin I have web server that shows the connected sensors on port 8080, you can change the port with this config option

port - Optional, port of web server to monitor devices, defaults to 8080

**Comment by chimcen** [comment]
Thank you - didn‘t recognize this option - when set the port to „80“ i got this:

[2018-9-7 08:00:07] [MCUIOT] Starting mDNS listener
[2018-9-7 08:00:07] Homebridge is running on port 51826.
[2018-9-7 08:00:07] [MCUIOT] Web Server listening on: http://localhost:80
[2018-9-7 08:00:07] [MCUIOT] Found MCUIOT device: NODE-41E2B
[2018-9-7 08:00:07] [MCUIOT] Skipping NODE-41E2B
[2018-9-7 08:00:17] [MCUIOT] HTTP get failed: NODE-41E2B ESOCKETTIMEDOUT

**Comment by chimcen** [comment]
Is it a problem because of usage of avahi?

But from my entire local network i get results from NodeMCU when browsing for this http://node-41e2b.local:80

Why is the plugin liatening at localhost:80 inatead of node-41e2b.local:80?

**Comment by NorthernMan54** [comment]
For port, please try 8081 and not 80.  Port 80 is a privileged port and requires the root when starting homebridge.

Besides the port bit, is everything okay?

**Comment by chimcen** [comment]
Ok, i've setup port 8081 in config.json and restarted the homebrige - result is the same.

[MCUIOT] Web Server listening on: http://localhost:8081
[MCUIOT] Found MCUIOT device: NODE-41E2B
[MCUIOT] Skipping NODE-41E2B
[MCUIOT] HTTP get failed: NODE-41E2B ESOCKETTIMEDOUT
[MCUIOT] Reading MCUIOT: NODE-41E2B
[MCUIOT] Reading MCUIOT: NODE-41E2B
[MCUIOT] Reading MCUIOT: NODE-41E2B
.....

When i type (pi user) wget `http://node-41e2b:8081` in terminal i'll receive a connection denied message... if'm do this with `http://node-41e2b:80` i'll get the sensor results read and saved correctly into index.html file on my raspberry...
I'm confused... :(


Yes, i've only get warnings because of using avahi, but as read in other posts, this seems to be ok...
The only thing is, why does the MCUIOT server is listening on "localhost..."?
In your tut the server is listening to Node-xxxx instead of localhost...

**Comment by NorthernMan54** [comment]
The web server listening on port 8081 has nothing to do with the error.

If you have esplorer connected to the nodemcu, what happens in the nodemcu console when the get fails?

For some reason the plugin is not getting a response from the nodemcu.  And I’m thinking the nodemcu may be crashing

**Comment by chimcen** [comment]
Actually i'm not at home - i'll check this tonight...

But when the nodemcu is crashed i couldn't get updates, but i'll do...

**Comment by NorthernMan54** [comment]
Tks that is pretty cool

I’m also wondering you if you are potential overloading the nodemcu?  The nodemcu  can only handle one connection at a time, and this error is what would happen if it was busy with another connection.  But as the plugin code polls the device every minute, subsequent requests should work.

**Comment by chimcen** [comment]
I don't think its a problem on nodemcu side - it must be a problem in software or interface...
Because i get date from it - 3 results with some timegap between:

***
{ "Hostname": "NODE-41E2B", "Model": "DHT", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 24.8, "Humidity": 56.8, "Moisture": 3, "Status": 0, "Barometer": -999, "Dew": -999 }}
.....
{ "Hostname": "NODE-41E2B", "Model": "DHT", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 24.8, "Humidity": 56.9, "Moisture": 2, "Status": 0, "Barometer": -999, "Dew": -999 }}
.....
{ "Hostname": "NODE-41E2B", "Model": "DHT", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 25, "Humidity": 56.5, "Moisture": 0, "Status": 0, "Barometer": -999, "Dew": -999 }}
***

In you blog your homebridge find the correct mdns and uses also port 80 and it works.
Why not on mine, too? :(
And why says my homebridge "Skipping NODE-41E2B" ?

**Comment by chimcen** [comment]
Started with div. ports a homebrigde instance with debugging:
[portDefault8080.txt](https://github.com/NorthernMan54/homebridge-mcuiot/files/2362153/portDefault8080.txt)
[port8081.txt](https://github.com/NorthernMan54/homebridge-mcuiot/files/2362159/port8081.txt)
[port80.txt](https://github.com/NorthernMan54/homebridge-mcuiot/files/2362161/port80.txt)

Loga from node-mcu when server is fetching data will be send later today...

**Comment by NorthernMan54** [comment]
I’m just looking at the port 8081 and 80 logs, and it appears to working correctly.  What shows in the Home app?

That error message appears to be an issue with the first device poll, but afterwards I can see that the next poll is reading and updating temperature and humidity.

The log entry starting with skipping, is the plugin realizing that the device is already configured and skipping the initial setup steps again.

**Comment by chimcen** [comment]
The Message from nodemcu when connected to homebridge seems to be perfekt:
***
```
PORT OPEN 115200

Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.
„cÄò'oß$gnœãìcpìÇds$sdpûgàƒlcnã|ÄŒ�‡Žc„ò'oï
NodeMCU custom build by frightanic.com
	branch: master
	commit: f99f295d97ac3a4e147f601802d5869d9d2d3012
	SSL: false
	modules: adc,ads1115,bit,bme280,dht,file,gpio,http,i2c,mdns,net,node,sjson,tmr,uart,websocket,wifi
 build created on 2018-09-04 11:25
 powered by Lua 5.1.4 on SDK 2.2.1(cfd48f3)
Heap Available: -c 37600
Heap Available: -l 34312
Heap Available: -m 29536
Heap Available: -setup 24864
Booting...
Heap Available: -boot 24704
Setting Init Timer
Configuring Wifi ...
Heap Available: -start 24328
> Connecting to CCG ...
IP unavailable, Waiting...

====================================
Name is:         NODE-41E2B
ESP8266 mode is: 1
MAC address is:  3a:2b:78:04:1e:2b
IP is:           192.168.178.12
====================================
Registering service dht22 with mDNS
Web Server Started
GET / HTTP/1.1
host: node-41e2b.local.
Connection: close


Status: 0
Temp: 29.8
Humi: 48.4
Moisture: 0
Baro: -999
Dew: -999

GET / HTTP/1.1
host: node-41e2b.local.
Connection: close


Status: 0
Temp: 29.5
Humi: 48.5
Moisture: 0
Baro: -999
Dew: -999

GET / HTTP/1.1
host: node-41e2b.local.
Connection: close
```

**Comment by chimcen** [comment]
...now ist working - don't know why, but its working...
could be a bad microUSB cable wich doesn't support the nodemcu with enough power?

**Comment by NorthernMan54** [comment]
That’s great news, good luck

**Comment by chimcen** [comment]
Thx for all the help :)
Btw. what does the reset switch exactly?

**Comment by NorthernMan54** [comment]
As the plugin adds devices as it discovers them, you need a method of removing them.  So the reset button deletes devices that can’t be found.

**Comment by chimcen** [comment]
Pretty cool :)

**Comment by chimcen** [comment]
Jfi - i‘m stil getting the error
[MCUIOT] HTTP get failed: NODE-41E2B ESOCKETTIMEDOUT

But it works anyway...

**Comment by NorthernMan54** [comment]
Just after restarting homebridge or periodically during the day?

If it’s periodically during the day, it may be a network connectivity or nodemcu capacity issue.  I thought they could only handle one request at a time.

**Comment by chimcen** [comment]
Just after restarting the homebridge (and also after removing power from nodemcu - eg. for moving location). After then i use the reset switch and it works again without showing http error - only reading node-xxx appears. :)

Btw. if i‘m moving from a dht22 to bme280 - has to be this bme280 a i2c sensor only or must it possible to connect to spi?

**Comment by NorthernMan54** [comment]
Great

**Comment by chimcen** [comment]
Btw. if i‘m moving from a dht22 to bme280 - has to be this bme280 a i2c sensor only or must it possible to connect to spi?

**Comment by NorthernMan54** [comment]
My plugin uses i2c

**Comment by chimcen** [comment]
[MCUIOT] HTTP get failed: NODE-41E2B ESOCKETTIMEDOUT
still remains - but it works anyway... wired...
