### ISSUE TITLE
[Question] Digits after the comma

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-mcuiot#13]
Hi,

is there a way to shorten the measurement values to only one digit after the comma instead of actual two?

**Comment by NorthernMan54** [comment]
Are you referring to the json response object from the nodemcu device?  Yes it should be feasible to change the number of digits in the response object, the lua code on the device would need to be modified to change the precision of the response object.   

In the file main.lua you can see the calls to read the device, and generate the json message.

When I wrote that I didn’t change the precision returned by the sensor as I wanted it to leave it the the code plugin code to change adjust as needed.

**Comment by chimcen** [comment]
How could this be done? Sry, no idea about that...
