### ISSUE TITLE
[Question] Possibility of considering other types of sensors

### ISSUE THREAD

**Issue by fparrav** [NorthernMan54/homebridge-mcuiot#14]
First of all thank all the work for excellent plugin, it works perfectly.

Second, I would like to see the possibility of incorporating other types of sensors, such as an hc-sr501, and behaving as an independent accessory connected to the same ESP8266 board. It would be great to be able to indicate this through config.json.

Greetings.

**Comment by NorthernMan54** [comment]
Please check out my other plugin homebridge-wssensor, this one supports motion sensors etc.
