### ISSUE TITLE
Error at reading values frome BME280

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-mcuiot#15]
Hi,

i've used your code before and it worked.
I used it with an Wemos NodeMCU Mini D1 and a BME280 1.8-5V Breakoutboard (purple board with only 4 wire outputs - VCC,GND,SDA,SCL).

Today i've bought new of them, but received a BME280 1.71-3.6V Breakoutboard (purple board with 6 wire outputs - VCC,GND,SDA,SCL,CSB,SDD).

I've connected them as the "old" one - SDA=D6, SDL=D5, GND and VCC=3.3V.
I#ve also loaded the same firmware and the same config from the old one to the new one.

The board is connecting my WiFi and starts up a web server.
When i'd like to check the value readings in browser i'm only getting a read error:

```
------------------------------------
> dofile("test.lua");
Heap Available: -c 37960
Heap Available: -l 33992
Heap Available: -b 32512
Heap Available: -m 27192
Heap Available: -setup 22512
Booting...
Heap Available: -boot 22800
Setting Init Timer
Configuring Wifi ...
Heap Available: -start 22536
> Connecting to linksys ...
IP unavailable, Waiting...

============================================
Name is:         NODE-73ECAC
ESP8266 mode is: 1
MAC address is:  86:f3:eb:73:ec:ac
IP is:           192.168.1.102
============================================
Registering service dht22 with mDNS
Web Server Started
GET / HTTP/1.1
Host: 192.168.1.102
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
Accept-Language: de-de
DNT: 1
Accept-Encoding: gzip, deflate


BME280 Read Error %d	1
PANIC: unprotected error in call to Lua API (main.lua:44: attempt to concatenate a nil value)
-------------------------------------------------------
```

**Comment by NorthernMan54** [comment]
Sometimes it errors out on the first or second try.  Does it stable out?

**Comment by chimcen** [comment]
No, the result is always the same.
Figured out that my supplier send me a sensor module BMP280 instead of BME280 - this could be the reason, because BMP280 doesn't provide humidity.

When i'm receiving the real BME280 i'll report the changes...

**Comment by NorthernMan54** [comment]
Okay

**Comment by chimcen** [comment]
As previously assumed - the error was because of using a BMP280 instead of a BME280.
