### ISSUE TITLE
Humidity not displaying in Home

### ISSUE THREAD

**Issue by ToddGreenfield** [NorthernMan54/homebridge-mcuiot#19]
Been using with BME280 for months without issue, all worked well. Now the humidity doesn’t show up in the Home app but does show in Eve. I believe Humidity used to work in Home, but now shows “...”
Same exact thing happening with two different devices.

**Comment by NorthernMan54** [comment]
Todd,

That’s really weird as I haven’t noticed that with any of mine.  I’m on iOS 12, but haven’t updated versions of homebridge and the plugin in months.  What version of the plugin are you using?

Also, in the logging can you see what value is being passed for humidity.

**Comment by ToddGreenfield** [comment]
Problem solved and this can be closed as there is no issue. I recently had PRK done and had increased the text size on  my phone since I don't see up close well now. Apparently the elipses  is due the description "Current Relative Humidity" taking up too much space when using larger text.

**Comment by NorthernMan54** [comment]
Tks for the update
