### ISSUE TITLE
Error with latest lua files from git when not using a battery on adc pin

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-mcuiot#20]
Hi,

i've tested the latest git version on my nodemcu with a bem280 connected.
Idon't use a battery - i've connected my node with usb to a wallcharger.

I've setup model "bme" in config.lua, but when grab the data from the node i've receiving this error:

`PANIC: unprotected error in call to Lua API (main.lua:59: attempt to concatenate global 'batteryString' (a nil value))`

**Comment by NorthernMan54** [comment]
This was resolved by the latest version v0.1.54

**Comment by chimcen** [comment]
Works. Thank you.
