### ISSUE TITLE
"Error finding AP" on test.lua

### ISSUE THREAD

**Issue by mrvnklm** [NorthernMan54/homebridge-mcuiot#23]
I've uploaded all files in the described order to my nodemcu using ESPlorer (running on macOS). I always get the following message:

`
> dofile("test.lua");
Heap Available: -c 37280
Heap Available: -l 33432
Heap Available: -m 27384
Heap Available: -setup 22336
Booting...
Heap Available: -boot 22584
Setting Init Timer
Configuring Wifi ...
Heap Available: -start 22672
> Error finding AP
`

My passwords.lua file:
`-- Rename this to passwords.lua, and add your WIFI SSID and Password
local module = {}
module.SSID = {}
module.SSID["SSID1"] = { ssid="Stay Connected!", pwd = "password" }
return module`

**Comment by NorthernMan54** [comment]
In the passwords file it should be

> local module = {}
> 
> module.SSID = {}
> module.SSID["Stay Connected!"] = { ssid="Stay Connected!", pwd = "asdf1337" }
> 
> return module
>

**Comment by mrvnklm** [comment]
Outch, that makes so much sense now. Thank you!
