### ISSUE TITLE
Set offset for BME280

### ISSUE THREAD

**Issue by derbe89** [NorthernMan54/homebridge-mcuiot#24]
Hi, thanks for the great tutorial and scripts! 

I printed some enclosures and built 6 Tempsensor-Stations.
When putting them next to each other I'm getting different temps (one shows repeatedly 1°C too much). Is there a possibility to set a temp-offset per device? e.g "+1.0" oder "0.7"

**Comment by NorthernMan54** [comment]
You could go into bme.lua and on line 19, and your adjustment

Line 19 is

temp = T / 100

**Comment by chimcen** [comment]
Can be closed - because i've tried this some weeks ago the same way and it works.

Also its possible to use a fine adjustment when using eg. "101.7" instead of only "101".
But beware - use "." instead of "," !
