### ISSUE TITLE
Possibility to split sensors to see temperature and humidity as single items?

### ISSUE THREAD

**Issue by mrvnklm** [NorthernMan54/homebridge-mcuiot#25]
Is there a possibility to split the DHT readouts to have two badges, one for temperature, one for humidity? For me it quite unhandy to click 3-4 times to see the humidity in the settings.

Another question, is it possible to use DHT22 with BME on one nodemcu? Connected it, but Barometer shows -999

**Comment by NorthernMan54** [comment]
It is feasible to split them but would require some coding effort.  As I’m up to the eyeballs in other things, and may not be able to get to this for a while, I would gladly accept a pull request implementing this feature.

**Comment by NoTrace-Kai** [comment]
Hi there ...
I am also interested in that feature.
But I don't know how to pull a request ;)
Thanks a lot for your work, it is a great project!
CU Kai

**Comment by mafyata** [comment]
Will you make new version with temp and humidity in seperate badges ?

**Comment by mrvnklm** [comment]
@NoTrace-Kai @mafyata 
I would recommend using MQTT protocol to make it work so you can easily add any sensor with any value you want
For your NodeMCU I recommend [ESPEasy](https://github.com/letscontrolit/ESPEasy)
and as Homebridge plugin [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing)
There are many tutorials on how to use / install MQTT (mosquitto) broker if you are not using it already, I am using at for all all my switches, sensors and so on.

**Comment by mafyata** [comment]
I use ravensystem/ravencore. In settings on eve app I set device type to 14. I have one button for temp and one for humidity. And if you want to delete it , you can :)

**Comment by mafyata** [comment]
![3E52E544-8A55-4C2D-B9E3-2514C1D70520](https://user-images.githubusercontent.com/48009267/58097982-49f28780-7be1-11e9-871f-8af719ed429c.png)
