### ISSUE TITLE
Some beginner documentation

### ISSUE THREAD

**Issue by agruen** [NorthernMan54/homebridge-mcuiot#27]
@NorthernMan54 not sure the best place to put this, but I'm running a seminar at the [Berkman-Klein Center](cyber.harvard.edu) on IoT and am teaching homebridge-mcuiot... As a result, I put together some[ documentation designed for absolute beginners](http://workingpaper.co/blog/node-mcu-instructions).  You're welcome to it -- and I'm happy to tweak if you have an idea for making it better.

**Comment by NorthernMan54** [comment]
Tks for sharing this, it looks really good.  If you don’t mind I will add this link to the Readme as it will really help other new users.

**Comment by agruen** [comment]
Go for it.  Happy to put it wherever you think would be most helpful.  Just too me too long to combine a bunch of different resources into one place... Thought others would benefit :)

**Comment by NorthernMan54** [comment]
I was thinking of just putting the link to your current hosting, or should it pull it into the Repo, and have GitHub host it.  I also have a website as well, but it is used for my Alexa skill.  And I could drop the content there as well.

Https://www.homebridge.ca

**Comment by agruen** [comment]
Sure thing, link away! everything is already on GitHub anyway (workingpaper.co is a GitHub pages site).  If you want, I can replicate the content into the Wiki in the project, or just do a pull request and add an extra page here, too.

At some point, I'll also do an ultra-beginner-guide to setting up homebridge in docker on a raspberry pi zero w (that's what I'm directing folks to do in the seminar).

**Comment by NorthernMan54** [comment]
I was thinking about the this for further and the wiki makes perfect sense as it’s very close to the code, and don’t have to worry about hosting issues, and gives people a perfect method of contact in case of issues.

**Comment by agruen** [comment]
I'll pop it up tonight.

**Comment by agruen** [comment]
I might be dense... But I can't figure out how to add a page to a wiki that doesn't yet exist?  Can you initialize the wiki?

**Comment by NorthernMan54** [comment]
Done

**Comment by agruen** [comment]
And in the longest thread ever to do something incredibly simple: https://help.github.com/en/articles/changing-access-permissions-for-wikis

Sorry, I didn't realize it wouldn't let me edit! 🤦‍♂️

**Comment by NorthernMan54** [comment]
Lol, is this a picnic or a id10t problem?

I made yourself a colaborator and removed the restriction to just collaborators 
![150f9992-139d-4b37-b8b9-11cf3505c4c4](https://user-images.githubusercontent.com/19808920/53854192-d310ff80-3f9e-11e9-9a61-2e434717c0d2.png)

**Comment by agruen** [comment]
🥳

All set!

At the moment, I'm linking to images and files hosted by me -- if you want to upload them to the repo to host them here, feel free.  All zipped up [here](https://workingpaper.co/files-for-nodemcu-iot.zip).

Happy to continue doing this kind of thing if there are places people get continually tripped up.

**Comment by NorthernMan54** [comment]
That looks spectacular, thanks again.

When I back from vacation next week, I will update the README etc

**Comment by agruen** [comment]
👍

So, I ran the seminar today, and learned a few things:

1. People struggled to download all the Lua files.  Can we zip them all, and add that zip to the repo, then link to it from the wiki? (instead of downloading the files, they repeatedly downloaded the entire html GitHub page...)
2. ESPlorer is tough.  Do you know if there's anything better? (I doubt it, but figured it's worth asking)  This weekend, I might play with that part of the wiki to add more screenshots...
3. Folks are blown away by this stuff.  Turns out it's a _great_ intro into hardware hacking!

**Comment by NorthernMan54** [comment]
Here is something to ponder a bit, this is my latest nodemcu package I worked on in December to support Xmas lights etc.

It features ota provisioning after initial load, and uses a script to download the initial files.  My documentation on this is a bit less user friendly, and at this time it deploys an led strip controller but pieces could be backported to mcuiot.  My vision was to deprecate my mcuiot and wssensor code bases, and migrate all to this, then I got distracted with my NodeRed and Alexa projects.

**Comment by NorthernMan54** [comment]
Also a big congrats

**Comment by agruen** [comment]
OK, that's _super_ interesting.  I'm on the plane back home, can't mess with it now.  Let me see if I can get it working this weekend (I assume I can just use the NodeMCU bits to see how it works, without having the lighting equipment?)... If it works like I'm reading, could be a _huge_ advance in usability.  And, looks like it might even be bash-scriptable? (Except for the single ESPlorer step...). I can already see a pi hole-like installer...

**Comment by NorthernMan54** [comment]
Just an FYI - I have updated the README, and pointed to the WIKI now for build instructions and have also given yourself credit for the documentation.  And have also changed the "working papers" links to ones in the REPO itself.  Tks very much again.
