### ISSUE TITLE
How can i remove a Sensor from Homekit?

### ISSUE THREAD

**Issue by NoTrace-Kai** [NorthernMan54/homebridge-mcuiot#28]
Hi there ...
I switched a NodeMCU and now i can not remove the old Sensor from the Homekit.
Alse they will be shown on the Webseite of mcuit.
NODE-53CF55 | Error | timeout | timeout
NODE-53DA15 | Error | timeout | timeout
I delet the entries in the config.json, but they are already shown in the Home app and on the website.
Can you please help me?!
Thanks a lot ... Kai

**Comment by NorthernMan54** [comment]
The plugin creates a button/switch called ‘Reset Switch’ which removes devices that are not responding on the network.  If that doesn’t work, there always is removing the .homebridge/persist and .homebridge/accessories directories.  Side effect is that you will lose all existing homebridge devices and have to setup again.
