### ISSUE TITLE
Home App temperature 0.5°C steps BME 280

### ISSUE THREAD

**Issue by leonboe1** [NorthernMan54/homebridge-mcuiot#29]
Hi,
I recently set up Homebridge and noticed that the temperature displayed in the home app is not 100% accurate (20.3°C displayed as 20.5°C, 21.1°C as 21.0°C etc). Is there a way to change that?
Also, the barometer values are not showing up.

Hope to get a reply,
Leon

**Comment by NorthernMan54** [comment]
@leonboe1 The rounding you are seeing are being done in the Home app and outside of my control.  Internally I'm sending values to 1 decimal point to HomeKit ie 18.1, but the Home app is rounding them.  If you use the Eve app, it doesn't round.  And will give you some nice graphs as well;-)

For barometric pressure, this characteristic is not supported by the Home app hence not visible.  It should be visible via the Eve app ( it was when I developed this ), but for some reason it has stopped displaying now.   Let me look further into why it stopped displaying

**Comment by leonboe1** [comment]
Okay, thanks for the quick reply! I know this question has already been asked but is there now a way to display temperature and humidity as separate accessories within the home app?

**Comment by NorthernMan54** [comment]
Not yet, but the Eve app displays them as separate icons

**Comment by leonboe1** [comment]
You're right, the Eve app works fine, even the pressure is displayed correctly. But I would prefer to have everything within just one app.
