### ISSUE TITLE
BME280/BMP280 Read Error

### ISSUE THREAD

**Issue by oldpeterhof** [NorthernMan54/homebridge-mcuiot#32]
I'm getting the following error regardless of whether I've got a BMP280 or BME280 lined up with my board. Any fix?

`BME280 Read Error %d	nil`
`PANIC: unprotected error in call to Lua API (main.lua:56: attempt to concatenate a nil value)`

**Comment by NorthernMan54** [comment]
That error is a device read error, is it connected correctly etc?

**Comment by oldpeterhof** [comment]
Haha well I forgot to include websocket in my NodeMCU build. This is what happens when you stay up too late. Thanks for the reply. :)
