### ISSUE TITLE
Supported hardware

### ISSUE THREAD

**Issue by jos149** [NorthernMan54/homebridge-mcuiot#36]
In the documentation it is mentioned I need a ESP8266 supported device. Mainly, the NodeMCU device is mentioned as this device. My question is: is it possible to flash my Wemos D1 mini with the firmware to function with the homebridge-mcuiot? And if I can flash this; is there anything different in flashing to a NodeMCU? The wemos d1 mini also has a ESP8266 so I guess it should be supported. And: is it easy to flash my wemos back to its original firmware?

Thanks in advance

**Comment by NorthernMan54** [comment]
As the Wemos D1 Mini is an ESP8266 it is 100% doable to flash this device.  I just don't have any experience with them, so really can't comment on the differences.  From my experience getting the correct pins mapped would be the first issue.

In regards to restoring the original firmware back on the Wemos, with my devices I have never tried to do a rollback so can't comment.

**Comment by jos149** [comment]
So pin mapping can be a problem you say. I want to connect a BME280 to send my temp/humid to my homebridge server over wifi. This sensor is i2c so I guess I just need to connect the correct pins right? I mean to say: the wemos d1 mini only has two hardware reserved dedicated i2c ports so cant be wrong right? Or do you see a problem here?

In that case it might be better to just order a few NodeMCU devices maybe? I that case I can just flash them and hook up a BME280 to them (guess they're also i2c enabled).

Restoring the original firmware isn't really a big problem, i was just wondering. Otherwise I will order a new one haha!

**Comment by NorthernMan54** [comment]
Why not just start with your wemos d1 mini and see where it takes you.  Worst case you run into a snag and switch to something else.  But I don't think you will have an issue as a lot of other people are using them.

**Comment by jos149** [comment]
Totally agree. Thanks for helping out!
