### ISSUE TITLE
bme280.init deprecated

### ISSUE THREAD

**Issue by screwb0x** [NorthernMan54/homebridge-mcuiot#4]
bme280.init is deprecated in bme.lua. bmetest.lua, test.lua and init.lua not working with newest NodeMCU Firmware

**Comment by NorthernMan54** [comment]
@screwb0x I just updated bme.lua to support the newest NodeMCU Firmware.  Please try again

**Comment by NorthernMan54** [comment]
Fixed in v0.1.50
