### ISSUE TITLE
Red LED blinking when device is queried, LED state = 2

### ISSUE THREAD

**Issue by Techno-Babble** [NorthernMan54/homebridge-mcuiot#6]
Setting the LED state to 2 in config.lua seems like it should result in LED activity only when the device is booting or an error has occurred. However, while the blue LED remains off, the red LED blinks whenever the device is queried.
```
-- LED state
module.ledState = 2 -- 0: fully disabled, 1: LEDs on, 2: Connected off (Boot/Error only)
```
Configured for DHT with DHT22 attached.
Curl output:
```
{ "Hostname": "NODE-XXXXXX", "Model": "DHT", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 19.8, "Humidity": 48.6, "Moisture": 0, "Status": 0, "Barometer": -999, "Dew": -999 }}
```

**Comment by NorthernMan54** [comment]
@awein I think this was from your pull request, could you look into it?

**Comment by awein** [comment]
@NorthernMan54 I'll have an other look within the next few days.
I had a quick look and I think I missed to disable `flashRed()` for `ledState` `2`.

@Techno-Babble you could give `ledState = 0` a try until this is fixed if you want to get rid of the flash on access.

**Comment by NorthernMan54** [comment]
@Techno-Babble If you can let @awein know if this fixes the issue, much appreciated.

**Comment by Techno-Babble** [comment]
@awein Confirmed this has fixed it! Thanks
